[workspace]
resolver = "2"
members = ["aarch64", "lab"]

[workspace.dependencies]
aarch64 = { path = "aarch64" }
bitfield-struct = { version = "0.4", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
