[package]
name = "aarch64-lab"
version = "0.1.0"
edition = "2021"

[dependencies]
aarch64.workspace = true
aarch64-cpu.workspace = true
bitfield-struct.workspace = true
tock-registers.workspace = true
zerocopy.workspace = true
